export const Products = [
  {
    id: 1,
    title: "iPhone 9",
    price: 549,
    stock: 94,
    category: "smartphones",
    thumbnail:
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-card-40-iphone14pro-202209_FMT_WHH?wid=508&hei=472&fmt=p-jpg&qlt=95&.v=1663611329204",
  },
  {
    id: 2,
    title: "iPhone X",
    price: 899,
    stock: 34,
    category: "smartphones",
    thumbnail:
      "https://cdn.vox-cdn.com/thumbor/r_cTogtuBDNZw_IRfbsEfmcnxj0=/0x0:1920x1280/2000x1333/filters:focal(960x640:961x641)/cdn.vox-cdn.com/uploads/chorus_asset/file/11249379/jbareham_171101_2099_A_0088_02.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    price: 1249,
    stock: 36,
    category: "smartphones",
    thumbnail:
      "https://cdn.shopify.com/s/files/1/2551/9654/products/5_e11ba5ee-75ee-4456-a9e8-13cf49aee5e8_480x480.jpg?v=1633852867",
  },
  {
    id: 4,
    title: "OPPOF19",
    price: 280,
    stock: 123,
    category: "smartphones",
    thumbnail:
      "https://image.oppo.com/content/dam/oppo/product-asset-library/f19-pro/f19-pro-overview-v1/v1/assets/kv-1920.jpg",
  },
  {
    id: 5,
    title: "Huawei P30",
    price: 499,
    stock: 32,
    category: "smartphones",
    thumbnail:
      "https://www.huaweicentral.com/wp-content/uploads/2022/01/Huawei-p30-jan-2022-update.jpg",
  },
  {
    id: 6,
    title: "MacBook Pro",
    price: 1749,
    stock: 83,
    category: "laptops",
    thumbnail:
      "https://www.abizindia.in/images/thumbs/0000024_apple-macbook-pro-13-inch_550.jpeg",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    price: 1499,
    stock: 50,
    category: "laptops",
    thumbnail:
      "https://images.indianexpress.com/2022/03/GalaxyBook2_Pro_360.jpg",
  },
  {
    id: 8,
    title: "Microsoft Surface Laptop 4",
    price: 1499,
    stock: 68,
    category: "laptops",
    thumbnail:
      "https://i0.wp.com/witchdoctor.co.nz/wp-content/uploads/2021/05/surface-laptop-4-3.jpg?ssl=1",
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    price: 1099,
    stock: 96,
    category: "laptops",
    thumbnail: "https://gagadget.com/media/uploads/Infinix%20INBook%20X1-1.jpg",
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    price: 1099,
    stock: 89,
    category: "laptops",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUplozEot8GjLhdbgyGk0xVAoBTb_Y0bfWuQ&usqp=CAU",
  },
  {
    id: 11,
    title: "perfume Oil",
    price: 13,
    stock: 65,
    category: "fragrances",
    thumbnail:
      "https://4.imimg.com/data4/CN/QT/MY-2816737/floral-bouquet-fragrance-oil-500x500.jpg",
  },
  {
    id: 12,
    title: "Brown Perfume",
    price: 40,
    stock: 52,
    category: "fragrances",
    thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
  },
  {
    id: 13,
    title: "Fog Scent Xpressio Perfume",
    price: 1300,
    stock: 61,
    category: "fragrances",
    thumbnail:
      "https://www.bigbasket.com/media/uploads/p/l/40046726-9_1-fogg-scent-xtremo-for-men.jpg",
  },
  {
    id: 14,
    title: "Non-Alcoholic Perfume Oil",
    price: 120,
    stock: 114,
    category: "fragrances",
    thumbnail: "https://m.media-amazon.com/images/I/81yUUNcPwYL._SL1500_.jpg",
  },
  {
    id: 15,
    title: "Eau De Perfume Spray",
    price: 30,
    stock: 105,
    category: "fragrances",
    thumbnail:
      "https://img.loccitane.com/ocms/img/lib/_2013_StaticContent/OCC_4678627ae1a64e8ea33a3b6702fbeb4f.jpg",
  },
  {
    id: 16,
    title: "Hyaluronic Acid Serum",
    price: 19,
    stock: 110,
    category: "skincare",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvqGLcmdY70mgCh4_wL-aJ1X6g1kXjVgDgNw&usqp=CAU",
  },
  {
    id: 17,
    title: "Tree Oil 30ml",
    price: 12,
    stock: 78,
    brand: "Hemani Tea",
    category: "skincare",
    thumbnail:
      "http://cdn.shopify.com/s/files/1/0588/3016/0078/products/Bhramarah_TeaTreeOil_32c7419c-55b7-4afa-8cf4-1d7a4ededd2f.jpg?v=1666337476",
  },
  {
    id: 18,
    title: "Oil Free Moisturizer 100ml",
    price: 40,
    stock: 88,
    brand: "Dermive",
    category: "skincare",
    thumbnail:
      "https://www.starhealth.in/blog/wp-content/uploads/2022/03/Tea-Tree-Oil-1.jpg",
  },
  {
    id: 19,
    title: "Skin Beauty Serum.",
    price: 46,
    stock: 54,
    brand: "ROREC White Rice",
    category: "skincare",
    thumbnail:
      "https://www.nykaa.com/beauty-blog/wp-content/uploads/images/issue305/beauty-stash_OI.jpg",
  },
  {
    id: 20,
    title: "Freckle Treatment Cream- 15gm",
    price: 70,
    stock: 140,
    category: "skincare",
    thumbnail: "https://m.media-amazon.com/images/I/513OmxEmUAL.jpg",
  },
  {
    id: 21,
    title: "- Daal Masoor 500 grams",
    price: 20,
    stock: 133,
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
  },
  {
    id: 22,
    title: "Elbow Macaroni - 400 gm",
    price: 14,
    stock: 146,
    brand: "Bake Parlor Big",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
  },
  {
    id: 23,
    title: "Orange Essence Food Flavou",
    price: 14,
    stock: 26,
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
  },
  {
    id: 24,
    title: "cereals muesli fruit nuts",
    price: 46,
    stock: 113,
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
  },
  {
    id: 25,
    title: "Gulab Powder 50 Gram",
    price: 70,
    stock: 47,
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
  },
  {
    id: 26,
    title: "Plant Hanger For Home",
    price: 41,
    stock: 131,
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
  },
  {
    id: 27,
    title: "Flying Wooden Bird",
    price: 51,
    stock: 17,
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
  },
  {
    id: 28,
    title: "3D Embellishment Art Lamp",
    price: 20,
    stock: 54,
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
  },
  {
    id: 29,
    title: "Handcraft Chinese style",
    price: 60,
    discountPercentage: 15.34,
    rating: 4.44,
    stock: 7,
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
  },
  {
    id: 30,
    title: "Key Holder",
    price: 30,
    stock: 54,
    category: "home-decoration",
    thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
  },
];
